name = "cf-do-collaborative-markdown-editor"
type = "javascript"
zone_id = ""
account_id = "3057da790214b3f8023628d382636e03"
route = ""
workers_dev = true
compatibility_date = "2021-12-09"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{ name = "docs", class_name = "DurableDoc" }]

[[migrations]]
tag = "v1"
new_classes = ["DurableDoc"]
